# server config
server:
  port: 8001

#database config
spring:
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: C##TOGATHER
      password: TOGATHER
      
# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
  
  
  
  
  
  
  
  