# server config
server:
  port: 8002

# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    jdbc-type-for-null: 'NULL'
  
spring:
# database config
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: C##TOGATHER
    password: TOGATHER
  mail:
    host: smtp.gmail.com
    port: 587
    username: com.greedy.to.gather@gmail.com
    password: xnrpej0609
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
  mvc:
    converters:
      preferred-json-mapper: gson
    
# file upload config
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      location: D:/semi-project/To-Gather_Files/To-Gather/
      

# image upload directory (이미지를 저장할 경로 설정)
image:
  image-dir: src/main/resources/upload/

  
# log level
logging: 
  level:
# root - 전역 설정
    root: info # 기본값
  
 
  